server:
  port: ${PORT:8082}

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME}
    password: ${CLEARDB_PASSWORD}
    hikari:
      maximum-pool-size: 15  # Adjust this value based on your needs
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!

---

spring:
  config:
    activate:
      on-profile: "qa"
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME}
    password: ${CLEARDB_PASSWORD}
    hikari:
      maximum-pool-size: 15  # Adjust this value based on your needs
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME}
    password: ${CLEARDB_PASSWORD}
    hikari:
      maximum-pool-size: 15  # Adjust this value based on your needs
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!