server:
  port: ${PORT:8082}

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: ${CLEARDB_DATABASE_URL:jdbc:mysql://localhost:3306/dcbapp}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME:root}
    password: ${CLEARDB_PASSWORD:D@tabase125##}
    hikari:
      maximum-pool-size: 30  # Adjust according to your database limits
      minimum-idle: 10
      idle-timeout: 30000  # milliseconds
      pool-name: SpringBootHikariCP
      connection-timeout: 20000  # milliseconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!

---

spring:
  config:
    activate:
      on-profile: "qa"
  datasource:
    url: ${CLEARDB_DATABASE_URL:jdbc:mysql://localhost:3306/dcbapp}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME:root}
    password: ${CLEARDB_PASSWORD:D@tabase125##}
    hikari:
      maximum-pool-size: 30  # Adjust according to your database limits
      minimum-idle: 10
      idle-timeout: 30000  # milliseconds
      pool-name: SpringBootHikariCP
      connection-timeout: 20000  # milliseconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${CLEARDB_DATABASE_URL:jdbc:mysql://localhost:3306/dcbapp}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CLEARDB_USERNAME:root}
    password: ${CLEARDB_PASSWORD:D@tabase125##}
    hikari:
      maximum-pool-size: 30  # Adjust according to your database limits
      minimum-idle: 10
      idle-timeout: 30000  # milliseconds
      pool-name: SpringBootHikariCP
      connection-timeout: 20000  # milliseconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
welcome:
  message: Database Connected!!